---
- include_vars: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - pip

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Apt signing key from ZM
  apt_key:
    url: https://zmrepo.zoneminder.com/debian/archive-keyring.gpg
    state: present

- name: Adding zm repo
  apt_repository:
    repo: deb https://zmrepo.zoneminder.com/debian/release-1.34 buster/
    update_cache: yes

- name: installing the required packages
  apt:
    name: "{{ required_packages }}"
    state: present
  tags:
    - packages

- name: Install pip modules
  pip:
    name: "{{ pip_modules }}"
    executable: /usr/bin/pip3
  tags:
    - pip

- name: update timzezone of php
  ansible.builtin.lineinfile:
    path: "{{ php_ini_file }}"
    regexp: ';date.timezone ='
    line: 'date.timezone = America/Los_Angeles'
  tags:
    - php

- name: start apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: copy secure sql file
  copy:
    src: mysql_secure_installation.sql
    dest: "~/"
    owner: root
    group: root
    mode: 0755
  tags:
    - secure_mysql

- name: secure mysql db
  mysql_db:
    name: all
    target: "~/mysql_secure_installation.sql"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: import
    login_user: root
  tags:
    - secure_mysql

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install zoneminder
  apt:
    name: zoneminder

- name: Add  user
  user:
    name: www-data
    group: video

- name: create zoneminder storage folder
  file:
    state: directory
    path: "{{ zm_data_dir }}/events"
    recurse: yes
    owner: www-data
    group: www-data
    mode: 0775

#- name: delay start of zoneminder
#  pause:
#    minutes: 2

- name: Enabling required apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ apache2_modules }}"

- name: Enabling required apache2 configuration
  shell: "a2enconf zoneminder"
  notify: "{{ item }}"
  with_items:
    - "reload apache2"

- name: update zoneminder.service
  ansible.builtin.lineinfile:
    path: "{{ zoneminder_service }}"
    regexp: '#User=www-data'
    line: 'User=www-data'

- name: update path swap to /dev/shm
  ansible.builtin.lineinfile:
    path: "{{ system-paths }}"
    regexp: 'ZM_PATH_SWAP='
    line: 'ZM_PATH_SWAP=/dev/shm'

- name: update permissions of zm.conf
  file:
    path: "{{ zm_conf }}"
    owner: www-data
    group: www-data
    mode: 0775

- name: start zoneminder
  service:
    name: zoneminder
    state: started
    enabled: yes

- name: apache2 tweaks
  include_tasks: "apache2.yml"
  tags:
    - never
    - apache2
