---
- include_vars: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - pip

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Apt signing key from ZM
  apt_key:
    url: https://zmrepo.zoneminder.com/debian/archive-keyring.gpg
    state: present

- name: Adding zm repo
  apt_repository:
    repo: deb https://zmrepo.zoneminder.com/debian/release-1.34 buster/
    update_cache: yes

- name: installing the required packages
  apt:
    name: "{{ required_packages }}"
    state: present
  tags:
    - packages

- name: Install pip modules
  pip:
    name: "{{ pip_modules }}"
    executable: /usr/bin/pip3
  tags:
    - pip

- name: secure mysql db
  mysql_db:
    name: all
    target: mysql_secure_installation.sql
    state: import
    login_user: root
  tags:
    - secure_mysql

- name: Updating package list
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install zoneminder
  apt:
    name: zoneminder

- name: Add  user
  user:
    name: www-data
    group: video

- name: start zoneminder
  service:
    name: zoneminder
    state: started
    enabled: yes
    
- name: Enabling required apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ apache2_modules }}"

- name: Enabling required apache2 configuration
  shell: "a2enconf zoneminder"
  notify: "{{ item }}"
  with_items:
    - "reload apache2"
