---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: Debian10
    image: jrei/systemd-debian:10
    command: /sbin/init
    privileged: True
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
